### DISCUSSION TITLE
how to set correct config

### DISCUSSION THREAD

**Discussion by domerich** [cathiele/homeassistant-goecharger#76] [Q&A]
Unfortunatelly I do not understand the docu regardning the charge limit and the input select. Please help me
```
goecharger:
  chargers:
    - name: garage_rechts
      host: 192.168.178.140
      input_number:
      goecharger_charge_limit:
        name: Charge limit (kWh)
        min: 0
        max: 25
        step: 1
      input_select:
        goecharger_max_current:
          name: Max current
          options:
            - 6
            - 10
            - 16
```

**Comment by domerich** [comment]
ok I figured it out, you need to ignore the string error messages. in my case it looks like this

```
goecharger:
  chargers:
    - name: garage_rechts
      host: 192.168.178.140

    - name: garage_links
      host: 192.168.178.136
      correction_factor: 1.0

input_number:
  goecharger_charge_limit:
    name: Charge limit (kWh)
    min: 0
    max: 25
    step: 1

input_select:
  goecharger_max_current:
    name: Max current
    options:
      - 6
      - 10
      - 12
      - 14
      - 16
```
