### ISSUE TITLE
Allowing switching between 1-line or 3-line charging

### ISSUE THREAD

**Issue by Schaussi** [cathiele/homeassistant-goecharger#49]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
In addition to being able to service.set_max_current it would be great to also have an option like service.set_lines (1 or 3 phases).

**Describe alternatives you've considered**
Setting it manually via go-e app.

**Additional context**
Would give a good effort if you are using it in combination with PV. Switching to "one line mode" allows charging with lower power like 1000W (1 line) if there is not enough PV energy available, and dynamically increase up to 22 kW (3 lines).

Thank you!

**Comment by cathiele** [comment]
I don't have a charger with v2 API Support. But if someone would implement it i would merge/integrate it.

**Comment by cathiele** [comment]
See #40

**Comment by kolossboss** [comment]
Hi,
I have the same problem.

I'm not a programmer or similar :-) butAs a workaround, you can create a `command_line` switch in HA to switch the between phases. You need to activate http v2 api in the app.
Its far away from a perfect solution, but it works nearly for my need right now.

In the next release, you can create a manual button entity I think, that works better as a switch.

```
- platform: command_line
  switches:
    goe_rechts_1phase:
      command_on: "curl 'http://192.168.x.x/api/set?psm=1'"
    goe_rechts_3phasen:
      command_on: "curl 'http://192.168.x.x/api/set?psm=2'"
```
OR (not sure what works better)

```
- platform: command_line
  switches:
    goe_rechts_phases:
      command_on: "curl 'http://192.168.x.x/api/set?psm=1'"
      command_off: "curl 'http://192.168.x.x/api/set?psm=2'"
```

You can also create a `command_line` sensor to get a feedback. But its not a very useful value. I'm not sure how to do it. 

```
- platform: command_line
  name: goe_status_phasen
  command: "curl http://192.168.x.x/api/status?filter=fsp"
  scan_interval: 30
  command_timeout: 60
```

If anyone had an idea how to do it better, you are welcome to share :-)
