### ISSUE TITLE
pre- post- contactor mixed up?

### ISSUE THREAD

**Issue by maulwuff** [cathiele/homeassistant-goecharger#6]
My charger is connected to 230 Schuko with the adapter cable.
This is a glance I have set up:
```
columns: 3
entities:
  - entity: sensor.goecharger_111111_u_l1
  - entity: sensor.goecharger_111111_u_l2
  - entity: sensor.goecharger_111111_u_l3
  - entity: sensor.goecharger_111111_p_l1
  - entity: sensor.goecharger_111111_p_l2
  - entity: sensor.goecharger_111111_p_l3
  - entity: sensor.goecharger_111111_i_l1
  - entity: sensor.goecharger_111111_i_l2
  - entity: sensor.goecharger_111111_i_l3
  - entity: sensor.goecharger_111111_lf_l1
  - entity: sensor.goecharger_111111_lf_l2
  - entity: sensor.goecharger_111111_lf_l3
  - entity: sensor.goecharger_111111_pre_contactor_l1
  - entity: sensor.goecharger_111111_pre_contactor_l2
  - entity: sensor.goecharger_111111_pre_contactor_l3
  - entity: sensor.goecharger_111111_post_contactor_l1
  - entity: sensor.goecharger_111111_post_contactor_l2
  - entity: sensor.goecharger_111111_post_contactor_l3
show_icon: false
show_name: true
show_state: true
title: Phasenwerte
type: glance
```

it shows 
- u_l1 = 230V
- pre_contactor_l1 = Off
- pre_contactor_l3 = On

seems mixed up to me?
