### ISSUE TITLE
set max current does not work with firmware 033

### ISSUE THREAD

**Issue by DreadWings7963** [cathiele/homeassistant-goecharger#95]
I have followed the tutorial exactly, activated the 1.0 api on the charger v2 and the change via the link [192.168.x](http://192.168.14.15/mqtt?payload=amp=16).x/mqtt[?payload=amp=16](http://192.168.14.15/mqtt?payload=amp=16) also works.
Also if you change the value from the charger with the app, the input_selector items changes also.

To imitate, take a charger v2, activate api 1.0. add via the graphical interface. name the charger go-eCharger. item names should then be: "sensor.goecharger_go_echarger_charger_max_current"
then add the following code to configuration.yaml:
```
input_select:
  goecharger_max_current:
    name: Max current
    options:
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11
      - 12
      - 13
      - 14
      - 15
      - 16

```
then into automations.yaml:
```
- id: '1576914483212'
  alias: 'goecharger: set max current on charger based on input select'
  description: ''
  trigger:
  - entity_id: input_select.goecharger_max_current
    platform: state
  condition: []
  action:
  - data_template:
      max_current: '{{ states(''input_select.goecharger_max_current'') }}'
    service: goecharger.set_max_current
- id: '1576915266692'
  alias: 'goecharger: set max_current input_select based on charger value'
  description: ''
  trigger:
  - entity_id: sensor.goecharger_go_echarger_charger_max_current
    platform: state
  condition: []
  action:
  - data_template:
      entity_id: input_select.goecharger_max_current
      option: '{{ states.sensor.goecharger_go_echarger_charger_max_current.state }}'
    service: input_select.select_option
```

log info:
![image](https://github.com/cathiele/homeassistant-goecharger/assets/105646498/a6764a19-3589-46df-a706-54a7ded4b225)

newest version of homeassistant used and main version via hasc installed. 

can you guys please help me with the problem
